# Generated by Django 4.0.5 on 2022-07-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyofgrades',
            name='image',
            field=models.ImageField(upload_to='media/grades'),
        ),
        migrations.AlterField(
            model_name='parentsvotersid',
            name='image',
            field=models.ImageField(upload_to='media/parents'),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='image',
            field=models.ImageField(upload_to='media/registrations'),
        ),
        migrations.AlterField(
            model_name='scholarvotersid',
            name='image',
            field=models.ImageField(upload_to='media/scholars'),
        ),
        migrations.DeleteModel(
            name='ApplicationForm',
        ),
    ]
