# Generated by Django 4.0.5 on 2022-07-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0002_dataofgrants_kiloofplastic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataOfGrants',
            new_name='DateOfGrants',
        ),
    ]
