# Generated by Django 4.0.5 on 2022-07-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherinformation',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
